# typed: false
# frozen_string_literal: true

# Generated by agent-doc scripts/bump-homebrew-formula.py from the v0.35.452 SHA256SUMS.
# Do not edit by hand: the agent-doc Release workflow rewrites it on every tag.
class AgentDoc < Formula
  desc "Interactive document sessions with AI agents"
  homepage "https://github.com/btakita/agent-doc"
  version "0.35.452"
  license "MIT"

  # Darwin archives are operator-built after the tag (make release-macos-assets);
  # the next formula bump after they upload replaces this with macOS archives.
  depends_on :linux

  on_linux do
    on_intel do
      url "https://github.com/btakita/agent-doc/releases/download/v#{version}/agent-doc-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3d35d1fa1e7edfe69ef7af312f550608f9ccf58e78e87de84df6994435d41be3"
    end

    on_arm do
      url "https://github.com/btakita/agent-doc/releases/download/v#{version}/agent-doc-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "80aafa8f3f931d25e7f859b76a9d535c175393ade0deed72fc5f8244270e00dd"
    end
  end

  def install
    # GH #52: `agent-doc lib-path` resolves the cdylib as a sibling of the running
    # executable, and macOS reports the invoked symlink rather than its target. Keep
    # both files in libexec and expose bin/agent-doc as an exec wrapper so the
    # running executable is always libexec/agent-doc.
    library = OS.mac? ? "libagent_doc.dylib" : "libagent_doc.so"
    libexec.install "agent-doc", library
    bin.write_exec_script libexec/"agent-doc"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-doc --version")
    assert_match "#{libexec}/libagent_doc", shell_output("#{bin}/agent-doc lib-path")
  end
end
